### ISSUE TITLE
请问下点击悬浮提示的文字和方法在哪里定义？？？

### ISSUE THREAD

**Issue by 852675742** [bianmaren/uni-tooltips-example#1]
请问下点击悬浮提示的文字和方法在哪里定义？？？

**Comment by bianmaren** [comment]
传入一个数组：tooltipBtns:["今日","昨日","近一周","近一月"]

**Comment by 852675742** [comment]
感谢您百忙之中的回答，前面的我已经调试好了，现在唯一碰到一个问题就是，我列表里面需要显示，然后第一个能正确显示在文字的上下左右，但后续的数据就不会显示在文字的上下左右了，烦请帮忙看下怎么修正，万分感激！



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bianmaren/uni-tooltips-example"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月3日(星期二) 上午10:46
收件人:&nbsp;"bianmaren/uni-tooltips-example"<uni-tooltips-example@noreply.github.com&gt;;
抄送:&nbsp;"张春林"<852675742@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bianmaren/uni-tooltips-example] 请问下点击悬浮提示的文字和方法在哪里定义？？？ (#1)





 
传入一个数组：tooltipBtns:["今日","昨日","近一周","近一月"]

**Comment by bianmaren** [comment]
OK，好早之前写的插件，哈哈，没注意细节，我下午来改造升级下

**Comment by 852675742** [comment]
感谢您的百忙之中升级该插件，万分感谢，期待！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bianmaren/uni-tooltips-example"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月3日(星期二) 中午11:06
收件人:&nbsp;"bianmaren/uni-tooltips-example"<uni-tooltips-example@noreply.github.com&gt;;
抄送:&nbsp;"张春林"<852675742@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bianmaren/uni-tooltips-example] 请问下点击悬浮提示的文字和方法在哪里定义？？？ (#1)





 
OK，好早之前写的插件，哈哈，没注意细节，我下午来改造升级下

**Comment by bianmaren** [comment]
我测试没问题呀，我demo上传了

**Comment by 852675742** [comment]
好的，我稍后再测试一下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bianmaren/uni-tooltips-example"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月3日(星期二) 中午12:02
收件人:&nbsp;"bianmaren/uni-tooltips-example"<uni-tooltips-example@noreply.github.com&gt;;
抄送:&nbsp;"张春林"<852675742@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bianmaren/uni-tooltips-example] 请问下点击悬浮提示的文字和方法在哪里定义？？？ (#1)





 
我测试没问题呀，我demo上传了

**Comment by 852675742** [comment]
您好：
&nbsp; &nbsp; &nbsp; 我刚测试了，当页面出现滚动条的时候，列表点击就会出现错位了，我刚把demo里面的循环次数改成100，然后点击第23条时，就不对了，大佬麻烦帮忙看下，万分感激。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bianmaren/uni-tooltips-example"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月3日(星期二) 中午12:02
收件人:&nbsp;"bianmaren/uni-tooltips-example"<uni-tooltips-example@noreply.github.com&gt;;
抄送:&nbsp;"张春林"<852675742@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bianmaren/uni-tooltips-example] 请问下点击悬浮提示的文字和方法在哪里定义？？？ (#1)





 
我测试没问题呀，我demo上传了

**Comment by bianmaren** [comment]
提交了，你再看看demo

**Comment by 852675742** [comment]
好的，我再测试一下，谢谢了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bianmaren/uni-tooltips-example"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月3日(星期二) 下午2:46
收件人:&nbsp;"bianmaren/uni-tooltips-example"<uni-tooltips-example@noreply.github.com&gt;;
抄送:&nbsp;"张春林"<852675742@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bianmaren/uni-tooltips-example] 请问下点击悬浮提示的文字和方法在哪里定义？？？ (#1)





 
提交了，你再看看demo

**Comment by 852675742** [comment]
感谢感谢大佬，迁移到项目中也无问题，已赞助，万分感激。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bianmaren/uni-tooltips-example"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月3日(星期二) 下午2:46
收件人:&nbsp;"bianmaren/uni-tooltips-example"<uni-tooltips-example@noreply.github.com&gt;;
抄送:&nbsp;"张春林"<852675742@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bianmaren/uni-tooltips-example] 请问下点击悬浮提示的文字和方法在哪里定义？？？ (#1)





 
提交了，你再看看demo

**Comment by 852675742** [comment]
您好，再请教下，如果想把那个箭头号放在右边，怎么改啊？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bianmaren/uni-tooltips-example"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月3日(星期二) 下午2:46
收件人:&nbsp;"bianmaren/uni-tooltips-example"<uni-tooltips-example@noreply.github.com&gt;;
抄送:&nbsp;"张春林"<852675742@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bianmaren/uni-tooltips-example] 请问下点击悬浮提示的文字和方法在哪里定义？？？ (#1)





 
提交了，你再看看demo

**Comment by bianmaren** [comment]
这个需要改偏移量计算，可以看看源码
